//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoU2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class direccion
    {
        public string cedula_di { get; set; }
        public string nombre_di { get; set; }
        public string apellido_paterno_di { get; set; }
        public string apellido_materno_di { get; set; }
        public string correo_di { get; set; }
        public string roles { get; set; }
        public string telefono { get; set; }
        public string ciudad_di { get; set; }
        public byte[] foto_di { get; set; }
        public string passwod_di { get; set; }
    }
}
