//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoU2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public paciente()
        {
            this.citas = new HashSet<cita>();
        }
    
        public int idPaciente { get; set; }
        public string cedula_pte { get; set; }
        public string nombre_pte { get; set; }
        public string apellido_paterno_pte { get; set; }
        public string apellido_materno_pte { get; set; }
        public string correo_pte { get; set; }
        public Nullable<System.DateTime> fNacimiento_pte { get; set; }
        public Nullable<int> edad_pte { get; set; }
        public string telefono_pte { get; set; }
        public string ciudad_pte { get; set; }
        public string direccion_pte { get; set; }
        public byte[] foto_pte { get; set; }
        public string usuario_pte { get; set; }
        public string passwod_pte { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cita> citas { get; set; }
    }
}
